spring.application.name=mailService
spring.mail.host-smtp.gmail.com
spring.mall.port-587
spring.mail.username=tutorial.genuinecoder@gmail.com
spring.mail.password=vityvvnzvisivimu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enabled=true
